server:
  port: 9090

spring:
  profiles:
    active: local

  jpa:
    open-in-view: false

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false

  logging:
    level: info
---

# h2
spring:
  profiles: local

  datasource:
    platform: h2
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
